### Listar todos os livros
GET http://localhost:8080/books
Accept: application/json


### Adicionar um novo livro
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Livro genérico",
  "author": "John Doec",
  "genre": "Software Engineering"
}

### Listar 1 livro especifico
GET http://localhost:8080/books/1
Accept: application/json

### Atualizar um livro existente
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Software Development"
}

### Deletar um livro
DELETE http://localhost:8080/books/2
